/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.BarraPorcentagem1;
//import telas.Principal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO IDEAPAD I3
 */
public class TelaCadastroCargaSaida extends javax.swing.JFrame {

    BarraPorcentagem1 barra = new BarraPorcentagem1();
    //Principal principal = new Principal();

    ImageIcon iconSalvar = new ImageIcon("C:\\Users\\LENOVO IDEAPAD I3\\Desktop\\nova\\apresentacao\\images\\Salvar32.png");
    Connection conn = null;
    Statement stmt;
    ResultSet rs;

    /**
     * Creates new form TelaCargaSaida
     */
    public TelaCadastroCargaSaida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codigoCarga = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        lblSalvar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Código da Carga:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 60, 110, 15);
        getContentPane().add(codigoCarga);
        codigoCarga.setBounds(169, 58, 118, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Data:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(125, 87, 40, 15);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(169, 84, 118, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Hora:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(125, 113, 40, 15);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(169, 110, 81, 20);

        btnSalvar.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalvarMouseExited(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(300, 60, 40, 40);

        lblSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSalvar.setForeground(new java.awt.Color(0, 255, 0));
        lblSalvar.setText("Salvar");
        getContentPane().add(lblSalvar);
        lblSalvar.setBounds(300, 100, 40, 14);

        setBounds(0, 0, 654, 218);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseEntered
        lblSalvar.setVisible(true);
    }//GEN-LAST:event_btnSalvarMouseEntered

    private void btnSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseExited
        lblSalvar.setVisible(false);

    }//GEN-LAST:event_btnSalvarMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblSalvar.setVisible(false);
        btnSalvar.setIcon(iconSalvar);
    }//GEN-LAST:event_formWindowOpened

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String sql;
        int valorCubico;
        int valor1=100;
        try {

            String var = codigoCarga.getText();

            Class.forName("com.mysql.jdbc.Driver");

            conn = DriverManager.getConnection("jdbc:mysql://localhost/dbenterprise", "root", "");
            sql = "SELECT valorCubico FROM entradaCarga WHERE matriculaCarga='" + var + "'";
            PreparedStatement ps;

            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery(sql);

            if (rs.next()) {
                valorCubico = rs.getInt("valorCubico");
           
               int variaveltxt = barra.lerTxtValor();
                valor1 = valorCubico - variaveltxt;
                String valor = Integer.toString(valor1);
                
                barra.escreverTxt(valor);

                jLabel2.setText(valor);

            } else {
                JOptionPane.showMessageDialog(rootPane, "erro");
            }

            //this.principal.setarBarraPorcentagem();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroCargaSaida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastroCargaSaida.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCargaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCargaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCargaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCargaSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCargaSaida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField codigoCarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblSalvar;
    // End of variables declaration//GEN-END:variables
}
